robot_state_publisher:
  ros__parameters:
    robot_description: |
      <?xml version="1.0" encoding="utf-8"?>
      <robot name="quadcopter">
        <link name="base_footprint"/>
        
        <joint name="base_joint" type="fixed">
          <parent link="base_footprint"/>
          <child link="base_link"/>
          <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
        </joint>
        
        <link name="base_link">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/base_link.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="silver">
              <color rgba="0.700 0.700 0.700 1.000"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/base_link.STL" scale="0.001 0.001 0.001"/>
            </geometry>
          </collision>
          <inertial>
            <origin xyz="0.0004 -0.0004 -0.0193" rpy="0 0 0"/>
            <mass value="0.150"/>
            <inertia ixx="0.0003" ixy="0.0000" ixz="0.0000" iyy="0.0003" iyz="0.0000" izz="0.0005"/>
          </inertial>
        </link>
        
        <joint name="propeller_1" type="continuous">
          <origin xyz="0.15 0.15 0.0" rpy="0 0 0"/>
          <parent link="base_link"/>
          <child link="link_propeller_1"/>
          <axis xyz="0 0 1"/>
        </joint>
        
        <link name="link_propeller_1">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_1.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="silver">
              <color rgba="0.700 0.700 0.700 1.000"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_1.STL" scale="0.001 0.001 0.001"/>
            </geometry>
          </collision>
          <inertial>
            <origin xyz="0.0000 0.0000 0.0019" rpy="0 0 0"/>
            <mass value="0.010"/>
            <inertia ixx="0.0000" ixy="0.0000" ixz="0.0000" iyy="0.0000" iyz="0.0000" izz="0.0000"/>
          </inertial>
        </link>
        
        <joint name="propeller_2" type="continuous">
          <origin xyz="-0.15 0.15 0.0" rpy="0 0 0"/>
          <parent link="base_link"/>
          <child link="link_propeller_2"/>
          <axis xyz="0 0 1"/>
        </joint>
        
        <link name="link_propeller_2">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="silver">
              <color rgba="0.700 0.700 0.700 1.000"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
          </collision>
          <inertial>
            <origin xyz="0.0000 0.0000 0.0019" rpy="0 0 0"/>
            <mass value="0.010"/>
            <inertia ixx="0.0000" ixy="0.0000" ixz="0.0000" iyy="0.0000" iyz="0.0000" izz="0.0000"/>
          </inertial>
        </link>
        
        <joint name="propeller_3" type="continuous">
          <origin xyz="-0.15 -0.15 0.0" rpy="0 0 0"/>
          <parent link="base_link"/>
          <child link="link_propeller_3"/>
          <axis xyz="0 0 1"/>
        </joint>
        
        <link name="link_propeller_3">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_3.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="silver">
              <color rgba="0.700 0.700 0.700 1.000"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_3.STL" scale="0.001 0.001 0.001"/>
            </geometry>
          </collision>
          <inertial>
            <origin xyz="0.0000 0.0000 0.0019" rpy="0 0 0"/>
            <mass value="0.010"/>
            <inertia ixx="0.0000" ixy="0.0000" ixz="0.0000" iyy="0.0000" iyz="0.0000" izz="0.0000"/>
          </inertial>
        </link>
        
        <joint name="propeller_4" type="continuous">
          <origin xyz="0.15 -0.15 0.0" rpy="0 0 0"/>
          <parent link="base_link"/>
          <child link="link_propeller_4"/>
          <axis xyz="0 0 1"/>
        </joint>
        
        <link name="link_propeller_4">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_4.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="silver">
              <color rgba="0.700 0.700 0.700 1.000"/>
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://quadcopter/meshes/link_propeller_4.STL" scale="0.001 0.001 0.001"/>
            </geometry>
          </collision>
          <inertial>
            <origin xyz="0.0000 0.0000 0.0019" rpy="0 0 0"/>
            <mass value="0.010"/>
            <inertia ixx="0.0000" ixy="0.0000" ixz="0.0000" iyy="0.0000" iyz="0.0000" izz="0.0000"/>
          </inertial>
        </link>
      </robot>