# ROS2-Gazebo Bridge Configuration for Quadcopter
# This file configures the bridge between Gazebo Garden and ROS2 for sensor data and motor control

# Motor Control Topics - ROS2 Control Controllers
- ros_topic_name: "/propeller_1_controller/commands"
  gz_topic_name: "/propeller_1_controller/commands"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/propeller_2_controller/commands"
  gz_topic_name: "/propeller_2_controller/commands"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/propeller_3_controller/commands"
  gz_topic_name: "/propeller_3_controller/commands"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/propeller_4_controller/commands"
  gz_topic_name: "/propeller_4_controller/commands"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# IMU Sensor Data - From Gazebo to ROS2
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Camera Data - From Gazebo to ROS2
- ros_topic_name: "/camera"
  gz_topic_name: "/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_info"
  gz_topic_name: "/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Joint States - From Gazebo to ROS2 (handled by ROS2 Control)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Clock Synchronization
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS